export const players = [
  { name: "alexander bah", position: "D", nacionality: "DK", age: "25" },
  { name: "andre gomes", position: "GR", nacionality: "PT", age: "18" },
  { name: "antonio silva", position: "D", nacionality: "PT", age: "19" },
  { name: "chiquinho", position: "M", nacionality: "PT", age: "27" },
  { name: "draxler", position: "A", nacionality: "DE", age: "29" },
  { name: "florentino", position: "M", nacionality: "PT", age: "23" },
  { name: "fredrik aursnes", position: "M", nacionality: "NO", age: "27" },
  { name: "gilberto", position: "D", nacionality: "PT", age: "30" },
  { name: "goncalo guedes", position: "A", nacionality: "PT", age: "26" },
  { name: "goncalo ramos", position: "A", nacionality: "PT", age: "21" },
  { name: "grimaldo", position: "D", nacionality: "ES", age: "27" },
  { name: "joao mario", position: "M", nacionality: "PT", age: "30" },
  { name: "joao neves", position: "M", nacionality: "PT", age: "18" },
  { name: "lucas verissimo", position: "D", nacionality: "BR", age: "27" },
  { name: "morato", position: "D", nacionality: "BR", age: "21" },
  { name: "neres", position: "A", nacionality: "BR", age: "26" },
  { name: "odysseas", position: "GR", nacionality: "GR", age: "29" },
  { name: "otamendi", position: "D", nacionality: "AR", age: "35" },
  { name: "petar musa", position: "A", nacionality: "CR", age: "25" },
  { name: "rafa", position: "A", nacionality: "PT", age: "30" },
  { name: "ristic", position: "D", nacionality: "SE", age: "27" },
  { name: "samuel soares", position: "GR", nacionality: "PT", age: "20" },
  { name: "schjelderup", position: "A", nacionality: "DE", age: "18" },
  { name: "tengstedt", position: "A", nacionality: "NO", age: "22" },
];

export const listPlayers = [
  "alexander bah",
  "andre gomes",
  "antonio silva",
  "chiquinho",
  "draxler",
  "florentino",
  "fredrik aursnes",
  "gilberto",
  "goncalo guedes",
  "goncalo ramos",
  "grimaldo",
  "joao mario",
  "joao neves",
  "lucas verissimo",
  "morato",
  "neres",
  "odysseas",
  "otamendi",
  "petar musa",
  "rafa",
  "ristic",
  "samuel soares",
  "schjelderup",
  "tengstedt",
];
